### ISSUE TITLE
Trim title in news item

### ISSUE THREAD

**Issue by grosa1** [grosa1/crypto-trading-toolkit-android#36]
![image](https://user-images.githubusercontent.com/28650772/87459369-97169180-c60b-11ea-9fae-371f287beac6.png)

**Comment by grosa1** [comment]
https://stackoverflow.com/questions/25247018/android-textview-singleline-field-hides-long-text/25247093

**Comment by ZappaBoy** [comment]
> -long-text/25247093

android:ellipsize="end"
